version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: fridayfinance
      POSTGRES_PASSWORD: fr1d4yf1n4nc3
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
       - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local